# Generated by Django 3.0.8 on 2020-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_latinword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latinword',
            name='words',
            field=models.CharField(db_index=True, max_length=255, verbose_name='单词列表'),
        ),
    ]
