# Generated by Django 3.0.8 on 2020-08-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20200827_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='latinword',
            name='sources',
            field=models.TextField(default=[], verbose_name='来源'),
        ),
    ]
