# Generated by Django 3.0.8 on 2020-08-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20200830_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordsearch',
            old_name='info',
            new_name='info_id',
        ),
        migrations.AlterUniqueTogether(
            name='wordsearch',
            unique_together={('word', 'info_id')},
        ),
    ]
