# Generated by Django 3.0.8 on 2020-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20200830_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latinword',
            name='main_attr',
            field=models.CharField(blank=True, choices=[('I Declension', '第一变格'), ('I and II Declension', '第一/第二变格'), ('II Declension', '第二变格'), ('III Declension', '第三变格'), ('IV Declension', '第四变格'), ('V Declension', '第五变格'), ('Indeclinable', ''), ('Irregular Declension', ''), ('Irregular', ''), ('I Conjugation', '第一变位'), ('II Conjugation', '第二变位'), ('III Conjugation', '第三变位'), ('IV Conjugation', '第四变位'), ('', '')], db_index=True, max_length=64, verbose_name='变位/变格'),
        ),
        migrations.AlterField(
            model_name='latinword',
            name='other_attrs',
            field=models.CharField(blank=True, choices=[('Masculine', '阳性'), ('Feminine', '阴性'), ('Neuter', '中性'), ('Common', ''), ('All/Other', ''), ('Positive', ''), ('Distributive', ''), ('Ablative', ''), ('Accusative', ''), ('Adverbial', ''), ('Cardinal', ''), ('Ordinal', ''), ('Genitive', ''), ('Superlative', '最高级'), ('Comparative', '比较级'), ('', '')], db_index=True, max_length=64, verbose_name='其他属性'),
        ),
    ]
