# Generated by Django 3.0.8 on 2020-07-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=128, unique=True, verbose_name='中文名')),
                ('english_name', models.CharField(max_length=128, unique=True, verbose_name='英语名')),
                ('sort_name', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='排序名')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='校名')),
                ('english_name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='英语校名')),
                ('chinese_name', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='中文校名')),
                ('sort_name', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='排序名')),
                ('raw_motto', models.CharField(max_length=1024, verbose_name='原始内容')),
                ('raw_motto_language', models.CharField(db_index=True, max_length=64, verbose_name='内容语言类型')),
                ('english_motto', models.CharField(blank=True, max_length=1024, verbose_name='英语翻译校训')),
                ('chinese_motto', models.CharField(blank=True, max_length=1024, verbose_name='中文翻译校训')),
                ('translate_status', models.CharField(choices=[('AUTO_TRANSLATE', '自动翻译'), ('CUSTOM_TRANSLATE', '自定义翻译')], default='AUTO_TRANSLATE', max_length=32, verbose_name='翻译状态')),
                ('status', models.CharField(choices=[('DELETED', '删除'), ('NORMAL', '正常'), ('HIDDEN', '隐藏')], db_index=True, default='NORMAL', max_length=32, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motto.Region')),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
