# Generated by Django 3.0.8 on 2020-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grammar',
            field=models.TextField(default='', verbose_name='词法及句法'),
        ),
    ]
