# Generated by Django 3.0.8 on 2020-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0002_school_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grammar',
            field=models.TextField(blank=True, default='', verbose_name='词法及句法'),
        ),
    ]
