# Generated by Django 3.0.8 on 2020-08-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20200830_1944'),
        ('motto', '0003_auto_20200830_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='MottoWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('extra', models.TextField(verbose_name='补充说明')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motto.School')),
                ('word_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.LatinWord')),
            ],
            options={
                'db_table': 'motto_word',
            },
        ),
    ]
