# Generated by Django 3.0.8 on 2020-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0005_auto_20200831_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos/', verbose_name='logo'),
        ),
    ]
