# Generated by Django 3.0.8 on 2020-09-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0007_auto_20200903_1007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mottoword',
            unique_together={('school', 'word')},
        ),
    ]
