# Generated by Django 3.0.8 on 2020-09-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20200830_1944'),
        ('motto', '0008_auto_20200903_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mottoword',
            unique_together={('school', 'word', 'word_info')},
        ),
    ]
