# Generated by Django 3.0.8 on 2020-09-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0010_auto_20200903_1050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mottoword',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mottoword',
            name='word_info',
        ),
    ]
