# Generated by Django 3.0.8 on 2020-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0012_mottoword_word_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mottoword',
            name='status',
            field=models.CharField(choices=[('DELETED', '删除'), ('NORMAL', '正常'), ('HIDDEN', '隐藏')], db_index=True, default='HIDDEN', max_length=32, verbose_name='状态'),
        ),
    ]
