# Generated by Django 3.0.8 on 2020-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0013_mottoword_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarAbbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=32, unique=True, verbose_name='缩写')),
                ('english_name', models.CharField(blank=True, max_length=64, verbose_name='缩写')),
                ('chinese_name', models.CharField(blank=True, max_length=64, verbose_name='缩写')),
                ('extra', models.CharField(blank=True, default='', max_length=512, verbose_name='补充说明')),
            ],
            options={
                'db_table': 'grammar_abbreviation',
            },
        ),
    ]
