# Generated by Django 3.0.8 on 2020-09-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0016_continent_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='sort',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
    ]
