# Generated by Django 3.0.8 on 2020-09-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0017_auto_20200920_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='extra',
            field=models.CharField(default='', max_length=512, verbose_name='额外信息'),
        ),
    ]
