# Generated by Django 3.0.8 on 2020-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0019_auto_20200927_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cn_sort_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='中文排序名'),
        ),
    ]
