# Generated by Django 3.0.8 on 2020-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motto', '0020_school_cn_sort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cn_sort_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='中文排序名'),
        ),
    ]
